#django/dockerfile
# 베이스 이미지
FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 종속성 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트 복사
COPY . .
ENV PYTHONPATH="${PYTHONPATH}:/app/database"
# 포트 개방
EXPOSE 8000

# 명령어
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:80"]